language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-ui" && yarn build:doc && yarn deploy:doc -- --username cozycloud --email contact@cozycloud.cc --repo=https://$GITHUB_TOKEN@github.com/cozy/cozy-ui.git
deploy:
  provider: npm
  email: npm@cozycloud.cc
  api_key:
    secure: eAJXf3L6DM6HNPzHs27PquK/HVIfE0T+lsM/7E6pFu5dL3q0X6A7cPE0bZ8U1VES+gie3HVxcTcNRG1sCkZJE85kqOhqj8IkFvzfD//5jObhET6JauA7xHUBR5JDhYmPNmrixGpIZpgCkc2UTmgngUQxY0zvQWtImZkgLtvzb5Q=
  on:
    tags: true
    repo: cozy/cozy-ui
env:
  global:
    secure: R3CSBrSNdBrL27FaZLw8KyshNreI9eArdXksT7Zf3oms/88mivudD0rSt5jYodPcMWF6IJtJ6xqqpJRbb/CH7eY7TOPoM9A2mhjxjy/tyk+UN4ieh75clCo/eMt89Zx6aJ72VZ0NsQAQHcOjA9UUm463HYpsGzzkc9dNGAM5F30=
